<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <Description>Static documentation hosting platform for Cocoar products</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cocoar.Configuration.AspNetCore" />
    <PackageReference Include="Cocoar.FileSystem" />
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>

</Project>
